import { createAsyncThunk, createSlice, PayloadAction } from '@reduxjs/toolkit';
import axios from 'axios';
import { NavigateFunction } from 'react-router-dom';
import Swal from 'sweetalert2/dist/sweetalert2.js';
interface UserInfo {
	email: string;
	password: string;
	error?: string | null;
}

interface UserInformationState {
	users: UserInfo[];
	loading: boolean;
	error?: string | null;
}

const initialState: UserInformationState = {
	users: [],
	loading: false,
	error: '',
};

export const loginUser = createAsyncThunk(
	'login/loginUser',
	async (
		payload: {
			loginData: UserInfo;
			t: (key: string) => string;
			navigate: NavigateFunction;
		},
		{ rejectWithValue }
	) => {
		const { loginData, t, navigate } = payload;
		try {
			const response = await axios.post<UserInfo[]>(
				'http://localhost:3000/api/v1/login',
				loginData
			);

			console.log(response.data);
			Swal.fire({
				title: 'Success!',
				text: 'Login Successfully!',
				confirmButtonText: 'Close',
				background: '#1e1e1e',
				color: '#1e1e1e',

				confirmButtonColor: '#1e1e1e',
			});

			navigate('/home');

			return response.data;
		} catch (error: unknown) {
			if (axios.isAxiosError(error)) {
				console.log(error);
				if (error.response?.status === 401) {
					return rejectWithValue(
						t('login_error.user_not_found') // Use the translation function here
					);
				}
			}
			return rejectWithValue(t('server_error'));
		}
	}
);

// Slice to handle actions generated by createAsyncThunk
export const loginSlice = createSlice({
	name: 'login',
	initialState,
	reducers: {
		resetError(state) {
			state.error = '';
		},
	},
	extraReducers: (builder) => {
		builder
			.addCase(loginUser.pending, (state) => {
				state.loading = true;
				console.log('Logging in the user...');
			})
			.addCase(
				loginUser.fulfilled,
				(state, action: PayloadAction<UserInfo[]>) => {
					state.loading = false;
					state.users = action.payload; // update users list
					console.log('User login successfully');
				}
			)
			.addCase(loginUser.rejected, (state, action) => {
				state.loading = false;
				state.error = action.payload as string;
				console.log('Error logging user:', action.payload);
			});
	},
});

export const { resetError } = loginSlice.actions;
export default loginSlice.reducer;
